### ISSUE TITLE
util.c:60:17: error: null destination pointer

### ISSUE THREAD

**Issue by tacerus** [johndoe31415/luksrku#1]
Hi!

Upon attempting to compile the program using `make`, I receive the following output:

```
$ make
cc -Wall -Wextra -Wshadow -Wswitch -Wpointer-arith -Wcast-qual -Wstrict-prototypes -Wmissing-prototypes -Werror=implicit-function-declaration -Werror=format -Wno-unused-parameter -O3 -std=c11 -pthread -D_POSIX_SOURCE -D_POSIX_C_SOURCE=200112L -D_XOPEN_SOURCE=500 -DBUILD_REVISION='"v0.03-11-g78a8cd70c2"' `pkg-config --cflags openssl` -ggdb3 -DDEBUG -fsanitize=address -fsanitize=undefined -fsanitize=leak -c -o util.o util.c
util.c: In function ‘sprintf_hex’:
util.c:60:17: error: null destination pointer [-Werror=format-overflow=]
   60 |                 sprintf(dest + (2 * i), "%02x", data[i]);
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: some warnings being treated as errors
make: *** [Makefile:60: util.o] Error 1
```

Unfortunately my C skills aren't good enough to debug it.

My environment:
- OpenSSL 1.1.1l 
- gcc 11.1.0
- GNU Make 4.3
- pkg-config 1.7.3

Any assistance would be highly appreciated.

Best,
Georg

**Comment by johndoe31415** [comment]
Hey Georg,

thanks for the report and in particular thanks for writing the compiler version.

Firstly a quick note: you're compiling the master (dev) branch, if you're trying to deploy a prod version, I'd recommend you use tag v0.04 (only change to current trunk is removal of libasan, which you don't want for prod).

To the error message you are seeing: It does not make any sense to me. The destination pointer to sprintf is only NULL if `dest` is NULL and that does never happen (the function is only called once and `dest` is a stack allocated string). So my best guess is that there's an overzealous compiler diagnostic in gcc 11 (I'm using gcc 10 for now).

However, I'll look into this, the function is short enough to post them on the gcc bugzilla if it's actually a compiler bug. For now I'd recommend you disable the diagnostic by removing the "-Werror=" parameter in the Makefile's CFLAGS and I'll see why this happens.

Cheers, Joe

**Comment by johndoe31415** [comment]
Hmm, this is super strange. I just installed gcc-11.1.0 as well over here and I am not seeing the same diagnostic you're seeing:

```
$ $CC -v
Using built-in specs.
COLLECT_GCC=gcc-11
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/11/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:amdgcn-amdhsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 11.1.0-1ubuntu1~21.04' --with-bugurl=file:///usr/share/doc/gcc-11/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++,m2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-11 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --enable-libphobos-checking=release --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --enable-cet --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-11-RPS7jb/gcc-11-11.1.0/debian/tmp-nvptx/usr,amdgcn-amdhsa=/build/gcc-11-RPS7jb/gcc-11-11.1.0/debian/tmp-gcn/usr --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu --with-build-config=bootstrap-lto-lean --enable-link-serialization=2
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 11.1.0 (Ubuntu 11.1.0-1ubuntu1~21.04) 

$ make clean all
[..]
gcc-11 -Wall -Wextra -Wshadow -Wswitch -Wpointer-arith -Wcast-qual -Wstrict-prototypes -Wmissing-prototypes -Werror=implicit-function-declaration -Werror=format -Wno-unused-parameter -O3 -std=c11 -pthread -D_POSIX_SOURCE -D_POSIX_C_SOURCE=200112L -D_XOPEN_SOURCE=500 -DBUILD_REVISION='"v0.04"' `pkg-config --cflags openssl` -c -o util.o util.c
gcc-11 -Wall -Wextra -Wshadow -Wswitch -Wpointer-arith -Wcast-qual -Wstrict-prototypes -Wmissing-prototypes -Werror=implicit-function-declaration -Werror=format -Wno-unused-parameter -O3 -std=c11 -pthread -D_POSIX_SOURCE -D_POSIX_C_SOURCE=200112L -D_XOPEN_SOURCE=500 -DBUILD_REVISION='"v0.04"' `pkg-config --cflags openssl` -c -o uuid.o uuid.c
gcc-11 -Wall -Wextra -Wshadow -Wswitch -Wpointer-arith -Wcast-qual -Wstrict-prototypes -Wmissing-prototypes -Werror=implicit-function-declaration -Werror=format -Wno-unused-parameter -O3 -std=c11 -pthread -D_POSIX_SOURCE -D_POSIX_C_SOURCE=200112L -D_XOPEN_SOURCE=500 -DBUILD_REVISION='"v0.04"' `pkg-config --cflags openssl` -c -o vaulted_keydb.o vaulted_keydb.c
gcc-11 -Wall -Wextra -Wshadow -Wswitch -Wpointer-arith -Wcast-qual -Wstrict-prototypes -Wmissing-prototypes -Werror=implicit-function-declaration -Werror=format -Wno-unused-parameter -O3 -std=c11 -pthread -D_POSIX_SOURCE -D_POSIX_C_SOURCE=200112L -D_XOPEN_SOURCE=500 -DBUILD_REVISION='"v0.04"' `pkg-config --cflags openssl` -c -o vault.o vault.c
gcc-11 -Wall -Wextra -Wshadow -Wswitch -Wpointer-arith -Wcast-qual -Wstrict-prototypes -Wmissing-prototypes -Werror=implicit-function-declaration -Werror=format -Wno-unused-parameter -O3 -std=c11 -pthread -D_POSIX_SOURCE -D_POSIX_C_SOURCE=200112L -D_XOPEN_SOURCE=500 -DBUILD_REVISION='"v0.04"' `pkg-config --cflags openssl` -o luksrku argparse_client.o argparse_edit.o argparse_server.o blacklist.o client.o editor.o exec.o file_encryption.o keydb.o log.o luks.o luksrku.o openssl.o pgmopts.o server.o signals.o thread.o udp.o util.o uuid.o vaulted_keydb.o vault.o `pkg-config --libs openssl`
```

This is super weird. Are you sure the code is entirely unmodified from v0.04?

**Comment by tacerus** [comment]
Hi John!

Thanks for the quick response!

I didn't realize there were tagged versions - my bad! After checking out the v0.04 one, it worked perfectly.

The master clone however, yes, I was originally sure it is unmodified/fresh.
But now that I cloned the master branch again, in order to try out your suggested modification of the CFLAGS, I could not reproduce the issue - it just worked, the same way it did with v0.04.

I cannot tell what happened, as there were no errors while cloning - maybe I missed something, or my machine happened to be hit with a [cosmic bit flip](https://en.wikipedia.org/wiki/Soft_error#Cosmic_rays_creating_energetic_neutrons_and_protons).

Either way, sorry for the circumstances caused, my apologies for the false alarm. and thank you for the great software!

**Comment by johndoe31415** [comment]
Hey Georg, no worries at all! I'm actually super happy someone is trying out that software and your bug report contained also all the info for me to quickly try to reproduce it. If you run into any issues at all or you see that error pop up again, please don't hesitate to reach out. Cheers! Joe

**Comment by tacerus** [comment]
Thank you! I appreciate it!

Cheers
Georg
